### ISSUE TITLE
Incompatile with mongodb version 3.6 ?

### ISSUE THREAD

**Issue by rajatsehgal2010** [torodb/stampede#224]
com.torodb.mongowp.exceptions.NoSuchKeyException: Missing expected field "indexes"

Everything is working but torodb shuts down after sometime. Please suggest any solution for version 3.6 mongodb.

When you are launching the new version of torodb compatible for mongodb 3.6 
Logtrace:
```
04:19:53.359 ERROR REPL       'oplog-applier-service-0'      c.t.m.r.MongoDbReplBundle      - Catched an error on the replication layer. Escalating it
04:19:53.359 ERROR LIFECYCLE  'oplog-applier-service-0'      c.t.s.StampedeService          - Error reported by replication supervisor. Stopping ToroDB Stampede
com.torodb.core.supervision.EscalatingException: com.torodb.mongodb.repl.oplogreplier.OplogApplier$UnexpectedOplogApplierException: com.torodb.core.retrier.RetrierGiveUpException: Unexpected exception while replying
	at com.torodb.mongodb.repl.ReplCoordinator.onError(ReplCoordinator.java:87) ~[repl-0.50.3.jar:?]
	at com.torodb.mongodb.repl.ReplCoordinator$OplogReplierServiceCallback.onError(ReplCoordinator.java:179) ~[repl-0.50.3.jar:?]
	at com.torodb.mongodb.repl.DefaultOplogApplierService.lambda$startUp$0(DefaultOplogApplierService.java:101) ~[repl-0.50.3.jar:?]
	at java.util.concurrent.CompletableFuture.uniAccept(CompletableFuture.java:656) [?:1.8.0_191]
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:632) [?:1.8.0_191]
	at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:442) [?:1.8.0_191]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_191]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_191]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_191]
Caused by: com.torodb.mongodb.repl.oplogreplier.OplogApplier$UnexpectedOplogApplierException: com.torodb.core.retrier.RetrierGiveUpException: Unexpected exception while replying
	at com.torodb.mongodb.repl.oplogreplier.AbstractApplyingJob.toTuple(AbstractApplyingJob.java:59) ~[repl-0.50.3.jar:?]
	at java.util.concurrent.CompletableFuture.uniHandle(CompletableFuture.java:822) ~[?:1.8.0_191]
	at java.util.concurrent.CompletableFuture$UniHandle.tryFire(CompletableFuture.java:797) ~[?:1.8.0_191]
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:474) ~[?:1.8.0_191]
	at java.util.concurrent.CompletableFuture.completeExceptionally(CompletableFuture.java:1977) ~[?:1.8.0_191]
	at scala.concurrent.java8.FuturesConvertersImpl$CF.apply(FutureConvertersImpl.scala:21) ~[scala-java8-compat_2.12-0.8.0.jar:?]
	at scala.concurrent.java8.FuturesConvertersImpl$CF.apply(FutureConvertersImpl.scala:18) ~[scala-java8-compat_2.12-0.8.0.jar:?]
	at scala.concurrent.impl.CallbackRunnable.run(Promise.scala:60) ~[scala-library-2.12.2.jar:?]
	at scala.concurrent.BatchingExecutor$Batch.processBatch$1(BatchingExecutor.scala:63) ~[scala-library-2.12.2.jar:?]
	at scala.concurrent.BatchingExecutor$Batch.$anonfun$run$1(BatchingExecutor.scala:78) ~[scala-library-2.12.2.jar:?]
	at scala.runtime.java8.JFunction0$mcV$sp.apply(JFunction0$mcV$sp.java:12) ~[scala-library-2.12.2.jar:?]
	at scala.concurrent.BlockContext$.withBlockContext(BlockContext.scala:81) ~[scala-library-2.12.2.jar:?]
	at scala.concurrent.BatchingExecutor$Batch.run(BatchingExecutor.scala:55) ~[scala-library-2.12.2.jar:?]
	at scala.concurrent.Future$InternalCallbackExecutor$.unbatchedExecute(Future.scala:864) ~[scala-library-2.12.2.jar:?]
	at scala.concurrent.BatchingExecutor.execute(BatchingExecutor.scala:106) ~[scala-library-2.12.2.jar:?]
	at scala.concurrent.BatchingExecutor.execute$(BatchingExecutor.scala:103) ~[scala-library-2.12.2.jar:?]
	at scala.concurrent.Future$InternalCallbackExecutor$.execute(Future.scala:862) ~[scala-library-2.12.2.jar:?]
	at scala.concurrent.impl.CallbackRunnable.executeWithValue(Promise.scala:68) ~[scala-library-2.12.2.jar:?]
	at scala.concurrent.impl.Promise$DefaultPromise.$anonfun$tryComplete$1(Promise.scala:284) ~[scala-library-2.12.2.jar:?]
	at scala.concurrent.impl.Promise$DefaultPromise.$anonfun$tryComplete$1$adapted(Promise.scala:284) ~[scala-library-2.12.2.jar:?]
	at scala.concurrent.impl.Promise$DefaultPromise.tryComplete(Promise.scala:284) ~[scala-library-2.12.2.jar:?]
	at scala.concurrent.Promise.tryFailure(Promise.scala:108) ~[scala-library-2.12.2.jar:?]
	at scala.concurrent.Promise.tryFailure$(Promise.scala:108) ~[scala-library-2.12.2.jar:?]
	at scala.concurrent.impl.Promise$DefaultPromise.tryFailure(Promise.scala:183) ~[scala-library-2.12.2.jar:?]
	at akka.stream.impl.fusing.GraphStages$IgnoreSink$$anon$9.onUpstreamFailure(GraphStages.scala:433) ~[akka-stream_2.12-2.5.2.jar:?]
	at akka.stream.impl.fusing.GraphInterpreter.processEvent(GraphInterpreter.scala:485) ~[akka-stream_2.12-2.5.2.jar:?]
	at akka.stream.impl.fusing.GraphInterpreter.execute(GraphInterpreter.scala:368) ~[akka-stream_2.12-2.5.2.jar:?]
	at akka.stream.impl.fusing.GraphInterpreterShell.runBatch(ActorGraphInterpreter.scala:571) ~[akka-stream_2.12-2.5.2.jar:?]
	at akka.stream.impl.fusing.ActorGraphInterpreter$SimpleBoundaryEvent.execute(ActorGraphInterpreter.scala:42) ~[akka-stream_2.12-2.5.2.jar:?]
	at akka.stream.impl.fusing.ActorGraphInterpreter$SimpleBoundaryEvent.execute$(ActorGraphInterpreter.scala:38) ~[akka-stream_2.12-2.5.2.jar:?]
	at akka.stream.impl.fusing.ActorGraphInterpreter$BatchingActorInputBoundary$OnNext.execute(ActorGraphInterpreter.scala:75) ~[akka-stream_2.12-2.5.2.jar:?]
	at akka.stream.impl.fusing.GraphInterpreterShell.processEvent(ActorGraphInterpreter.scala:546) ~[akka-stream_2.12-2.5.2.jar:?]
	at akka.stream.impl.fusing.ActorGraphInterpreter.akka$stream$impl$fusing$ActorGraphInterpreter$$processEvent(ActorGraphInterpreter.scala:725) ~[akka-stream_2.12-2.5.2.jar:?]
	at akka.stream.impl.fusing.ActorGraphInterpreter$$anonfun$receive$1.applyOrElse(ActorGraphInterpreter.scala:740) ~[akka-stream_2.12-2.5.2.jar:?]
	at akka.actor.Actor.aroundReceive(Actor.scala:513) ~[akka-actor_2.12-2.5.2.jar:?]
	at akka.actor.Actor.aroundReceive$(Actor.scala:511) ~[akka-actor_2.12-2.5.2.jar:?]
	at akka.stream.impl.fusing.ActorGraphInterpreter.aroundReceive(ActorGraphInterpreter.scala:650) ~[akka-stream_2.12-2.5.2.jar:?]
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:527) ~[akka-actor_2.12-2.5.2.jar:?]
	at akka.actor.ActorCell.invoke(ActorCell.scala:496) ~[akka-actor_2.12-2.5.2.jar:?]
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:257) ~[akka-actor_2.12-2.5.2.jar:?]
	at akka.dispatch.Mailbox.run(Mailbox.scala:224) ~[akka-actor_2.12-2.5.2.jar:?]
	... 3 more
Caused by: com.torodb.core.retrier.RetrierGiveUpException: Unexpected exception while replying
	at com.torodb.mongodb.repl.oplogreplier.batch.SimpleAnalyzedOplogBatchExecutor.visit(SimpleAnalyzedOplogBatchExecutor.java:116) ~[repl-0.50.3.jar:?]
	at com.torodb.mongodb.repl.oplogreplier.batch.SimpleAnalyzedOplogBatchExecutor.visit(SimpleAnalyzedOplogBatchExecutor.java:47) ~[repl-0.50.3.jar:?]
	at com.torodb.mongodb.repl.oplogreplier.batch.SingleOpAnalyzedOplogBatch.accept(SingleOpAnalyzedOplogBatch.java:41) ~[repl-0.50.3.jar:?]
	at com.torodb.mongodb.repl.oplogreplier.batch.AnalyzedOplogBatchExecutor.apply(AnalyzedOplogBatchExecutor.java:54) ~[repl-0.50.3.jar:?]
	at com.torodb.mongodb.repl.oplogreplier.DefaultOplogApplier.lambda$apply$e6a147fb$1(DefaultOplogApplier.java:141) ~[repl-0.50.3.jar:?]
	at akka.stream.javadsl.Source.$anonfun$map$1(Source.scala:941) ~[akka-stream_2.12-2.5.2.jar:?]
	at akka.stream.impl.fusing.Map$$anon$7.onPush(Ops.scala:47) ~[akka-stream_2.12-2.5.2.jar:?]
	at akka.stream.impl.fusing.GraphInterpreter.processPush(GraphInterpreter.scala:499) ~[akka-stream_2.12-2.5.2.jar:?]
	at akka.stream.impl.fusing.GraphInterpreter.processEvent(GraphInterpreter.scala:462) ~[akka-stream_2.12-2.5.2.jar:?]
	at akka.stream.impl.fusing.GraphInterpreter.execute(GraphInterpreter.scala:368) ~[akka-stream_2.12-2.5.2.jar:?]
	at akka.stream.impl.fusing.GraphInterpreterShell.runBatch(ActorGraphInterpreter.scala:571) ~[akka-stream_2.12-2.5.2.jar:?]
	at akka.stream.impl.fusing.ActorGraphInterpreter$SimpleBoundaryEvent.execute(ActorGraphInterpreter.scala:42) ~[akka-stream_2.12-2.5.2.jar:?]
	at akka.stream.impl.fusing.ActorGraphInterpreter$SimpleBoundaryEvent.execute$(ActorGraphInterpreter.scala:38) ~[akka-stream_2.12-2.5.2.jar:?]
	at akka.stream.impl.fusing.ActorGraphInterpreter$BatchingActorInputBoundary$OnNext.execute(ActorGraphInterpreter.scala:75) ~[akka-stream_2.12-2.5.2.jar:?]
	at akka.stream.impl.fusing.GraphInterpreterShell.processEvent(ActorGraphInterpreter.scala:546) ~[akka-stream_2.12-2.5.2.jar:?]
	at akka.stream.impl.fusing.ActorGraphInterpreter.akka$stream$impl$fusing$ActorGraphInterpreter$$processEvent(ActorGraphInterpreter.scala:725) ~[akka-stream_2.12-2.5.2.jar:?]
	at akka.stream.impl.fusing.ActorGraphInterpreter$$anonfun$receive$1.applyOrElse(ActorGraphInterpreter.scala:740) ~[akka-stream_2.12-2.5.2.jar:?]
	at akka.actor.Actor.aroundReceive(Actor.scala:513) ~[akka-actor_2.12-2.5.2.jar:?]
	at akka.actor.Actor.aroundReceive$(Actor.scala:511) ~[akka-actor_2.12-2.5.2.jar:?]
	at akka.stream.impl.fusing.ActorGraphInterpreter.aroundReceive(ActorGraphInterpreter.scala:650) ~[akka-stream_2.12-2.5.2.jar:?]
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:527) ~[akka-actor_2.12-2.5.2.jar:?]
	at akka.actor.ActorCell.invoke(ActorCell.scala:496) ~[akka-actor_2.12-2.5.2.jar:?]
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:257) ~[akka-actor_2.12-2.5.2.jar:?]
	at akka.dispatch.Mailbox.run(Mailbox.scala:224) ~[akka-actor_2.12-2.5.2.jar:?]
	... 3 more
Caused by: com.torodb.mongodb.repl.oplogreplier.OplogOperationApplier$OplogApplyingException: com.torodb.mongowp.exceptions.NoSuchKeyException: Mising expected field "indexes"
	at com.torodb.mongodb.repl.oplogreplier.OplogOperationApplier.applyCmd(OplogOperationApplier.java:230) ~[repl-0.50.3.jar:?]
	at com.torodb.mongodb.repl.oplogreplier.OplogOperationApplier.access$400(OplogOperationApplier.java:63) ~[repl-0.50.3.jar:?]
	at com.torodb.mongodb.repl.oplogreplier.OplogOperationApplier$Visitor.lambda$visit$0(OplogOperationApplier.java:133) ~[repl-0.50.3.jar:?]
	at com.torodb.mongodb.repl.oplogreplier.OplogOperationApplier.apply(OplogOperationApplier.java:91) ~[repl-0.50.3.jar:?]
	at com.torodb.mongodb.repl.oplogreplier.batch.SimpleAnalyzedOplogBatchExecutor.execute(SimpleAnalyzedOplogBatchExecutor.java:81) ~[repl-0.50.3.jar:?]
	at com.torodb.mongodb.repl.oplogreplier.batch.SimpleAnalyzedOplogBatchExecutor.visit(SimpleAnalyzedOplogBatchExecutor.java:114) ~[repl-0.50.3.jar:?]
	at com.torodb.mongodb.repl.oplogreplier.batch.SimpleAnalyzedOplogBatchExecutor.visit(SimpleAnalyzedOplogBatchExecutor.java:47) ~[repl-0.50.3.jar:?]
	at com.torodb.mongodb.repl.oplogreplier.batch.SingleOpAnalyzedOplogBatch.accept(SingleOpAnalyzedOplogBatch.java:41) ~[repl-0.50.3.jar:?]
	at com.torodb.mongodb.repl.oplogreplier.batch.AnalyzedOplogBatchExecutor.apply(AnalyzedOplogBatchExecutor.java:54) ~[repl-0.50.3.jar:?]
	at com.torodb.mongodb.repl.oplogreplier.DefaultOplogApplier.lambda$apply$e6a147fb$1(DefaultOplogApplier.java:141) ~[repl-0.50.3.jar:?]
	at akka.stream.javadsl.Source.$anonfun$map$1(Source.scala:941) ~[akka-stream_2.12-2.5.2.jar:?]
	at akka.stream.impl.fusing.Map$$anon$7.onPush(Ops.scala:47) ~[akka-stream_2.12-2.5.2.jar:?]
	at akka.stream.impl.fusing.GraphInterpreter.processPush(GraphInterpreter.scala:499) ~[akka-stream_2.12-2.5.2.jar:?]
	at akka.stream.impl.fusing.GraphInterpreter.processEvent(GraphInterpreter.scala:462) ~[akka-stream_2.12-2.5.2.jar:?]
	at akka.stream.impl.fusing.GraphInterpreter.execute(GraphInterpreter.scala:368) ~[akka-stream_2.12-2.5.2.jar:?]
	at akka.stream.impl.fusing.GraphInterpreterShell.runBatch(ActorGraphInterpreter.scala:571) ~[akka-stream_2.12-2.5.2.jar:?]
	at akka.stream.impl.fusing.ActorGraphInterpreter$SimpleBoundaryEvent.execute(ActorGraphInterpreter.scala:42) ~[akka-stream_2.12-2.5.2.jar:?]
	at akka.stream.impl.fusing.ActorGraphInterpreter$SimpleBoundaryEvent.execute$(ActorGraphInterpreter.scala:38) ~[akka-stream_2.12-2.5.2.jar:?]
	at akka.stream.impl.fusing.ActorGraphInterpreter$BatchingActorInputBoundary$OnNext.execute(ActorGraphInterpreter.scala:75) ~[akka-stream_2.12-2.5.2.jar:?]
	at akka.stream.impl.fusing.GraphInterpreterShell.processEvent(ActorGraphInterpreter.scala:546) ~[akka-stream_2.12-2.5.2.jar:?]
	at akka.stream.impl.fusing.ActorGraphInterpreter.akka$stream$impl$fusing$ActorGraphInterpreter$$processEvent(ActorGraphInterpreter.scala:725) ~[akka-stream_2.12-2.5.2.jar:?]
	at akka.stream.impl.fusing.ActorGraphInterpreter$$anonfun$receive$1.applyOrElse(ActorGraphInterpreter.scala:740) ~[akka-stream_2.12-2.5.2.jar:?]
	at akka.actor.Actor.aroundReceive(Actor.scala:513) ~[akka-actor_2.12-2.5.2.jar:?]
	at akka.actor.Actor.aroundReceive$(Actor.scala:511) ~[akka-actor_2.12-2.5.2.jar:?]
	at akka.stream.impl.fusing.ActorGraphInterpreter.aroundReceive(ActorGraphInterpreter.scala:650) ~[akka-stream_2.12-2.5.2.jar:?]
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:527) ~[akka-actor_2.12-2.5.2.jar:?]
	at akka.actor.ActorCell.invoke(ActorCell.scala:496) ~[akka-actor_2.12-2.5.2.jar:?]
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:257) ~[akka-actor_2.12-2.5.2.jar:?]
	at akka.dispatch.Mailbox.run(Mailbox.scala:224) ~[akka-actor_2.12-2.5.2.jar:?]
	... 3 more
Caused by: com.torodb.mongowp.exceptions.NoSuchKeyException: Mising expected field "indexes"
	at com.torodb.mongowp.utils.BsonReaderTool.getEntry(BsonReaderTool.java:145) ~[mongowp-core-0.50.2.jar:?]
	at com.torodb.mongowp.utils.BsonReaderTool.getArray(BsonReaderTool.java:221) ~[mongowp-core-0.50.2.jar:?]
	at com.torodb.mongowp.utils.BsonReaderTool.getArray(BsonReaderTool.java:209) ~[mongowp-core-0.50.2.jar:?]
	at com.torodb.mongodb.commands.signatures.admin.CreateIndexesCommand$CreateIndexesArgument.unmarshall(CreateIndexesCommand.java:133) ~[mongodb-core-0.50.3.jar:?]
	at com.torodb.mongodb.commands.signatures.admin.CreateIndexesCommand$CreateIndexesArgument.access$000(CreateIndexesCommand.java:95) ~[mongodb-core-0.50.3.jar:?]
	at com.torodb.mongodb.commands.signatures.admin.CreateIndexesCommand.unmarshallArg(CreateIndexesCommand.java:66) ~[mongodb-core-0.50.3.jar:?]
	at com.torodb.mongodb.commands.signatures.admin.CreateIndexesCommand.unmarshallArg(CreateIndexesCommand.java:48) ~[mongodb-core-0.50.3.jar:?]
	at com.torodb.mongowp.commands.impl.AbstractNotAliasableCommand.unmarshallArg(AbstractNotAliasableCommand.java:45) ~[mongowp-core-0.50.2.jar:?]
	at com.torodb.mongodb.repl.oplogreplier.OplogOperationApplier.applyCmd(OplogOperationApplier.java:228) ~[repl-0.50.3.jar:?]
	at com.torodb.mongodb.repl.oplogreplier.OplogOperationApplier.access$400(OplogOperationApplier.java:63) ~[repl-0.50.3.jar:?]
	at com.torodb.mongodb.repl.oplogreplier.OplogOperationApplier$Visitor.lambda$visit$0(OplogOperationApplier.java:133) ~[repl-0.50.3.jar:?]
	at com.torodb.mongodb.repl.oplogreplier.OplogOperationApplier.apply(OplogOperationApplier.java:91) ~[repl-0.50.3.jar:?]
	at com.torodb.mongodb.repl.oplogreplier.batch.SimpleAnalyzedOplogBatchExecutor.execute(SimpleAnalyzedOplogBatchExecutor.java:81) ~[repl-0.50.3.jar:?]
	at com.torodb.mongodb.repl.oplogreplier.batch.SimpleAnalyzedOplogBatchExecutor.visit(SimpleAnalyzedOplogBatchExecutor.java:114) ~[repl-0.50.3.jar:?]
	at com.torodb.mongodb.repl.oplogreplier.batch.SimpleAnalyzedOplogBatchExecutor.visit(SimpleAnalyzedOplogBatchExecutor.java:47) ~[repl-0.50.3.jar:?]
	at com.torodb.mongodb.repl.oplogreplier.batch.SingleOpAnalyzedOplogBatch.accept(SingleOpAnalyzedOplogBatch.java:41) ~[repl-0.50.3.jar:?]
	at com.torodb.mongodb.repl.oplogreplier.batch.AnalyzedOplogBatchExecutor.apply(AnalyzedOplogBatchExecutor.java:54) ~[repl-0.50.3.jar:?]
	at com.torodb.mongodb.repl.oplogreplier.DefaultOplogApplier.lambda$apply$e6a147fb$1(DefaultOplogApplier.java:141) ~[repl-0.50.3.jar:?]
	at akka.stream.javadsl.Source.$anonfun$map$1(Source.scala:941) ~[akka-stream_2.12-2.5.2.jar:?]
	at akka.stream.impl.fusing.Map$$anon$7.onPush(Ops.scala:47) ~[akka-stream_2.12-2.5.2.jar:?]
	at akka.stream.impl.fusing.GraphInterpreter.processPush(GraphInterpreter.scala:499) ~[akka-stream_2.12-2.5.2.jar:?]
	at akka.stream.impl.fusing.GraphInterpreter.processEvent(GraphInterpreter.scala:462) ~[akka-stream_2.12-2.5.2.jar:?]
	at akka.stream.impl.fusing.GraphInterpreter.execute(GraphInterpreter.scala:368) ~[akka-stream_2.12-2.5.2.jar:?]
	at akka.stream.impl.fusing.GraphInterpreterShell.runBatch(ActorGraphInterpreter.scala:571) ~[akka-stream_2.12-2.5.2.jar:?]
	at akka.stream.impl.fusing.ActorGraphInterpreter$SimpleBoundaryEvent.execute(ActorGraphInterpreter.scala:42) ~[akka-stream_2.12-2.5.2.jar:?]
	at akka.stream.impl.fusing.ActorGraphInterpreter$SimpleBoundaryEvent.execute$(ActorGraphInterpreter.scala:38) ~[akka-stream_2.12-2.5.2.jar:?]
	at akka.stream.impl.fusing.ActorGraphInterpreter$BatchingActorInputBoundary$OnNext.execute(ActorGraphInterpreter.scala:75) ~[akka-stream_2.12-2.5.2.jar:?]
	at akka.stream.impl.fusing.GraphInterpreterShell.processEvent(ActorGraphInterpreter.scala:546) ~[akka-stream_2.12-2.5.2.jar:?]
	at akka.stream.impl.fusing.ActorGraphInterpreter.akka$stream$impl$fusing$ActorGraphInterpreter$$processEvent(ActorGraphInterpreter.scala:725) ~[akka-stream_2.12-2.5.2.jar:?]
	at akka.stream.impl.fusing.ActorGraphInterpreter$$anonfun$receive$1.applyOrElse(ActorGraphInterpreter.scala:740) ~[akka-stream_2.12-2.5.2.jar:?]
	at akka.actor.Actor.aroundReceive(Actor.scala:513) ~[akka-actor_2.12-2.5.2.jar:?]
	at akka.actor.Actor.aroundReceive$(Actor.scala:511) ~[akka-actor_2.12-2.5.2.jar:?]
	at akka.stream.impl.fusing.ActorGraphInterpreter.aroundReceive(ActorGraphInterpreter.scala:650) ~[akka-stream_2.12-2.5.2.jar:?]
	at akka.actor.ActorCell.receiveMessage(ActorCell.scala:527) ~[akka-actor_2.12-2.5.2.jar:?]
	at akka.actor.ActorCell.invoke(ActorCell.scala:496) ~[akka-actor_2.12-2.5.2.jar:?]
	at akka.dispatch.Mailbox.processMailbox(Mailbox.scala:257) ~[akka-actor_2.12-2.5.2.jar:?]
	at akka.dispatch.Mailbox.run(Mailbox.scala:224) ~[akka-actor_2.12-2.5.2.jar:?]
	... 3 more
```

**Comment by teoincontatto** [comment]
Hi @rajatsehgal2010,

Can you enable stacktrace with [this log4j2.xml file](https://github.com/torodb/stampede/blob/v1.0.0/main/src/main/profiles/dev/log4j2.xml) and provide the full log with the stacktrace:

```
torodb-stampede --log4j2-file log4j2.xml
```

**Comment by rajatsehgal2010** [comment]
i have updated the issue with logtrace

**Comment by rajatsehgal2010** [comment]
@rajatsehgal2010  did it work ?

**Comment by imaginevinay** [comment]
@rajatsehgal2010  i think it supports mongo 3.4 only 
it is mentioned in the installation quick start. And please update your torodb to version 1.0.0 :)
